version: "3.9"

service:
  #Microservices images
  gateway-service:
    build: ./gateway
    ports:
      - "8000:8000"
    restart: always

  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    depends_on:
      - gateway-service
    restart: always
  
  userProfile-service:
    build: ./user_profile
    ports:
      - "5001:5001"
    depends_on:
      - gateway-service
      - auth-service
    restart: always

  itemManagement-service:
    build: ./item_management
    ports:
      - "4001:4001"
    depends_on:
      - gateway-service
      - auth-service
    restart: always

  ratingsAndReviews-service:
    build: ./ratingandreviews
    ports:
      - "4000:4000"
    depends_on:
      - gateway-service
      - auth-service
      - userProfile-service
      - itemManagement-service
    restart: always

  delivery-service:
    build: ./delivery/src/v1
    ports: 
      - "8004:8004"
    depends_on: 
      - gateway-service
      - auth-service
      - userProfile-service
      - itemManagement-service

  payment-service:
    build: ./payment/src/v1
    ports:
      - "8003:8003"
    depends_on:
      - gateway-service
      - auth-service
      - userProfile-service
      - itemManagement-service
      - delivery-service
    restart: always

  cart-service:
    build: ./cart
    ports: 
      - "8080:8080"
    depends_on:
      - gateway-service
      - auth-service
      - userProfile-service
      - itemManagement-service
    restart: always

  